import React from "react";
import styles from "./page.module.css";
import IllustrationsImg from "/public/illustration.png";
import WebsitesImg from "/public/websites.png";
import AppsImg from "/public/apps.jpg";
import GalerryItem from "./components/galerryItem/GalerryItem";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function Porfolio() {
  return (
    <main className={styles.main}>
      <h1>Choose a Galery</h1>
      <div className={styles.items}>
        <GalerryItem
          href={"Illustrations"}
          title="Illustrations"
          src={IllustrationsImg}
        />
        <GalerryItem href={"Websites"} title="Websites" src={WebsitesImg} />
        <GalerryItem href={"Applications"} title="Applications" src={AppsImg} />
      </div>
    </main>
  );
}
