import React from 'react'
import styles from './page.module.css'

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function Dashboard() {
  return (
    <main className={styles.main}>
      <h1>ეს არის დეშბორდი</h1>
    </main>
  )
}